nameOverride: cluster-autoscaler

autoDiscovery:
  enabled: true
  clusterName: seoul-dev-demo-eks

awsRegion: ap-northeast-2

extraArgs:
  v: 4
  stderrthreshold: info
  logtostderr: true
  expander: random
  scale-down-enabled: true
  scale-down-utilization-threshold: 0.75
  skip-nodes-with-local-storage: false
  skip-nodes-with-system-pods: false

sslCertPath: /etc/ssl/certs/ca-bundle.crt

rbac:
  create: true
  pspEnabled: true
