apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - image: nalbam/deepracer-timer:v0.0.17
          resources:
            limits:
              cpu: 120m
              memory: 153Mi
            requests:
              cpu: 100m
              memory: 128Mi
