apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deepracer-timer
    app.kubernetes.io/name: deepracer-timer
  name: deepracer-timer
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: 'nalbam/deepracer-timer:v0.0.15'
          name: deepracer-timer
          resources:
            limits:
              cpu: 120m
              memory: 153Mi
            requests:
              cpu: 100m
              memory: 128Mi
