apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-spring
spec:
  selector:
    matchLabels:
      app: sample-spring
  template:
    metadata:
      labels:
        app: sample-spring
        app.kubernetes.io/name: sample-spring
        version: v0.2.42
    spec:
      containers:
        - image: nalbam/sample-spring:v0.2.42
          name: sample-spring
          resources:
            limits:
              cpu: 600m
              memory: 614Mi
            requests:
              cpu: 500m
              memory: 512Mi
          envFrom:
            - configMapRef:
                name: sample-spring
