apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-spring
spec:
  selector:
    matchLabels:
      app: sample-spring
  template:
    metadata:
      labels:
        app: sample-spring
        app.kubernetes.io/name: sample-spring
        version: v0.2.35
    spec:
      containers:
        - image: nalbam/sample-spring:v0.2.35
          name: sample-spring
          resources:
            limits:
              cpu: 1200m
              memory: 1228Mi
            requests:
              cpu: 1000m
              memory: 1024Mi
          envFrom:
            - configMapRef:
                name: sample-spring
