apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: sample-node
    app.kubernetes.io/name: sample-node
  name: sample-node
data:
  PROFILE: dev
  VERSION: v0.2.26
  MESSAGE: hello dev-spot world
