apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: sample-node
    app.kubernetes.io/name: sample-node
  name: sample-node
data:
  PROFILE: 'dev'
  VERSION: v0.3.94
  MESSAGE: 'hello dev-spot world'
