apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: sample-webpack
    app.kubernetes.io/name: sample-webpack
  name: sample-webpack
data:
  PROFILE: prod
  VERSION: v0.0.0
  MESSAGE: hello prod-demo world
