replicaCount: 1
profile: default
image:
  repository: nalbam/sample-webpack
  tag: alpine
  pullPolicy: Always
labels: {}
annotations: {}
pod:
  labels: {}
  annotations: {}
pdb: {}
service:
  type: ClusterIP
  labels: {}
  annotations: {}
  externalPort: 80
  internalPort: 80
ingress:
  enabled: true
  labels: {}
  annotations: {}
  basedomain: 127.0.0.1.nip.io
hpa:
  enabled: true
  min: 1
  max: 5
  cpu: 80
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 150m
    memory: 256Mi
readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 3
  periodSeconds: 15
  failureThreshold: 6
livenessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 3
  periodSeconds: 15
  failureThreshold: 6
