replicaCount: 1

profile: default

namespace: default

image:
  repository: nalbam/sample-webpack
  tag: latest
  pullPolicy: Always

labels: {}
annotations: {}

pod:
  labels: {}
  annotations: {}

pdb: {}

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 80
  annotations: {}
  labels: {}

ingress:
  enabled: true
  hosts: {}
  # hosts:
  #   - sample-webpack.demo.nalbam.com
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  labels: {}

autoscaling:
  enabled: false
  min: 1
  max: 5
  cpu: 80
  memory:
  requests:

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 120m
    memory: 153Mi

readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 3
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 3
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3

# livenessProbe:
#   exec:
#     command:
#     - cat
#     - /tmp/healthy
#   initialDelaySeconds: 3
#   periodSeconds: 10
# livenessProbe:
#   tcpSocket:
#     port: 80
#   initialDelaySeconds: 3
#   periodSeconds: 10

# hostNetwork: true
# dnsPolicy: Default

nodeSelector: {}

tolerations: []

affinity: {}

env: {}
  # - name: MESSAGE
  #   value: "hello world"

configmap:
  enabled: false
  data: {}
    # MESSAGE: "hello world"

secret:
  enabled: false
  data: {}
    # SECRET: "c2VjcmV0IHdvcmxkCg=="
