apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: sample-spring
    app.kubernetes.io/name: sample-spring
  name: sample-spring
data:
  PROFILE: prod
  VERSION: v0.3.46
  MESSAGE: hello prod-demo world
  JAVA_AGENT_ENABLED: "true"
