apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: sample-spring
    app.kubernetes.io/name: sample-spring
  name: sample-spring
spec:
  # replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: sample-spring
  strategy:
    canary:
      canaryService: sample-spring-preview
      steps:
        - setWeight: 25
        - analysis:
            # templates:
            #   - templateName: http-benchmark
            templateName: http-benchmark
            args:
              - name: url
                value: http://sample-spring-preview:8080/success/98
  template:
    metadata:
      labels:
        app: sample-spring
        app.kubernetes.io/name: sample-spring
        version: v0.4.5
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
    spec:
      containers:
        - image: nalbam/sample-spring:v0.4.5
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: sample-spring
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: jmx
              containerPort: 8081
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 550m
              memory: 1Gi
          envFrom:
            - configMapRef:
                name: sample-spring
