apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: sample-spring
    app.kubernetes.io/name: sample-spring
    release: prometheus-operator
  name: sample-spring
spec:
  selector:
    matchLabels:
      app: sample-spring
  endpoints:
    - interval: 30s
      path: /actuator/prometheus
      port: http
