# https://argoproj.github.io/argo-rollouts/features/analysis/

apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
    - name: namespace
    - name: service
  metrics:
    - name: success-rate
      provider:
        prometheus:
          address: http://prometheus-server.monitor.svc.cluster.local:9090
          query: |
            sum(rate(nginx_ingress_controller_requests{namespace=~"{{args.namespace}}",service=~"{{args.service}}",status!~"[4-5].*"}[2m]))
            /
            sum(rate(nginx_ingress_controller_requests{namespace=~"{{args.namespace}}",service=~"{{args.service}}"}[2m]))
      interval: 10s
      successCondition: result >= 0.90
      # failureLimit: 3
