apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: me@nalbam.com
    privateKeySecretRef:
      name: letsencrypt-issuer-prod
    http01: {}
