apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
    - name: namespace
    - name: service
  metrics:
    - name: success-rate
      interval: 10s
      successCondition: result >= 0.95
      failureLimit: 3
      provider:
        prometheus:
          address: http://prometheus-server.monitor:9090
          query: |
            sum( irate(
              nginx_ingress_controller_requests{namespace=~"{{args.namespace}}",service=~"{{args.service}}",status!~"[4-5].*"}[2m]
            ) ) /
            sum( irate(
              nginx_ingress_controller_requests{namespace=~"{{args.namespace}}",service=~"{{args.service}}"}[2m]
            ) )
