apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-webpack
spec:
  selector:
    matchLabels:
      app: sample-webpack
  template:
    metadata:
      labels:
        app: sample-webpack
        app.kubernetes.io/name: sample-webpack
    spec:
      containers:
        - image: nalbam/sample-webpack:v0.1.7
          name: sample-webpack
          resources:
            limits:
              cpu: 120m
              memory: 153Mi
            requests:
              cpu: 100m
              memory: 128Mi
          envFrom:
            - configMapRef:
                name: sample-webpack
