apiVersion: v1
kind: LimitRange
metadata:
  name: sample-dev-limits
spec:
  limits:
  - default:
      cpu: 250m
      memory: 1024Mi
    min:
      cpu: 100m
      memory: 100Mi
    max:
      cpu: 800m
      memory: 1Gi
    defaultRequest:
      cpu: 250m
      memory: 1024Mi
    type: Container
