apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: sample-spring
    app.kubernetes.io/name: sample-spring
  name: sample-spring
data:
  PROFILE: dev
  VERSION: v0.2.44
  MESSAGE: hello spot-dev world
