apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: sample-node
    app.kubernetes.io/name: sample-node
  name: sample-node
data:
  PROFILE: prod
  VERSION: v0.2.17
  MESSAGE: hello prod-demo world
