apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: sample-node
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sample-node
  strategy:
    canary:
      steps:
        - setWeight: 20
        # The following pause step will pause the rollout indefinitely until manually resumed.
        # Rollouts can be manually resumed by running `kubectl argo rollouts resume ROLLOUT`
        - pause: {}
        - setWeight: 40
        - pause: { duration: 40 }
        - setWeight: 60
        - pause: { duration: 20 }
        - setWeight: 80
        - pause: { duration: 20 }
  template:
    metadata:
      labels:
        app: sample-node
        app.kubernetes.io/name: sample-node
    spec:
      containers:
        - image: nalbam/sample-node:v0.2.27
          name: sample-node
          resources:
            limits:
              cpu: 120m
              memory: 153Mi
            requests:
              cpu: 100m
              memory: 128Mi
          envFrom:
            - configMapRef:
                name: sample-node
