apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: sample-node
    app.kubernetes.io/name: sample-node
  name: sample-node
spec:
  minReplicas: 4
  maxReplicas: 8
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: sample-node
  # targetCPUUtilizationPercentage: 80
  metrics:
    - type: Pods
      pods:
        metricName: container_network_receive_bytes
        targetAverageValue: 100k
