#
# CircleCI 2.0
#
version: 2
jobs:
  build:
    docker:
      - image: opspresso/gitops
    steps:
      - checkout
      - run:
          name: Build
          command: |
            bash ./build.sh

workflows:
  version: 2
  apply:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
# https://circleci.com/docs/2.0/add-ssh-key/
