#
# CircleCI 2.0
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: Build
          command: |
            pip3 install git-pull-request
            bash ./build.sh

# workflows:
#   version: 2
#   apply:
#     jobs:
#       - build
