#
# CircleCI 2.0
#
version: 2
jobs:
  build:
    docker:
      - image: opspresso/builder
    steps:
      - add_ssh_keys:
          fingerprints:
            - "0f:7c:d3:cf:b8:b7:cd:36:88:20:e0:53:82:fe:0f:12"
      - checkout
      - run:
          name: Build
          command: |
            bash ./build.sh

# workflows:
#   version: 2
#   apply:
#     jobs:
#       - build
