{{ if and (not (empty .Values.istio)) (not (empty .Values.canary)) }}
{{ if and (.Values.istio.enabled) (.Values.canary.enabled) }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "fullname" . }}
spec:
  hosts:
    - {{ include "fullname" . }}
  http:
  - route:
    - destination:
        host: {{ include "fullname" . }}
        subset: stable
      weight: 90
    - destination:
        host: {{ include "fullname" . }}
        subset: canary
      weight: 10
{{ end }}
{{ end }}
