{{ if and (not (empty .Values.istio)) (not (empty .Values.canary)) }}
{{ if and (.Values.istio.enabled) (.Values.canary.enabled) }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "fullname" . }}
spec:
  hosts:
    - {{ template "fullname" . }}
  http:
  - route:
    - destination:
        host: {{ template "fullname" . }}
        subset: master
      weight: 90
    - destination:
        host: {{ template "fullname" . }}
        subset: canary
      weight: 10
{{ end }}
{{ end }}
