{{ if (not (empty .Values.istio)) }}
{{ if (.Values.istio.enabled) }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ template "fullname" . }}-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "fullname" . }}-gateway
spec:
  hosts:
  - "*"
  gateways:
  - {{ template "fullname" . }}-gateway
  http:
  - route:
    - destination:
        host: {{ template "fullname" . }}
        port:
          number: {{ .Values.service.externalPort }}
    match:
    - uri:
        exact: /spring
    - uri:
        exact: /stress
    - uri:
        prefix: /dealy
    - uri:
        prefix: /timeout
{{ end }}
{{ end }}
