{{ if and (not (empty .Values.istio)) (not (empty .Values.canary)) }}
{{ if and (.Values.istio.enabled) (not .Values.canary.enabled) }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "fullname" . }}
spec:
  host: {{ include "fullname" . }}
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 1024
        http2MaxRequests: 1024
        maxRequestsPerConnection: 10
    outlierDetection:
      consecutiveErrors: 5
      interval: 10s
      baseEjectionTime: 30s
      maxEjectionPercent: 10
  subsets:
  - name: stable
    labels:
      version: stable
{{ end }}
{{ end }}
