apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: sample-tomcat
    app.kubernetes.io/name: sample-tomcat
  name: sample-tomcat
data:
  PROFILE: prod
  VERSION: v0.3.13
  MESSAGE: hello prod-demo world
