apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-tomcat
spec:
  template:
    spec:
      containers:
        - image: nalbam/sample-tomcat:v0.1.5
          name: sample-tomcat
          resources:
            limits:
              cpu: 1200m
              memory: 1228Mi
            requests:
              cpu: 1000m
              memory: 1024Mi
          envFrom:
            - configMapRef:
                name: sample-tomcat
