apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-tomcat
spec:
  selector:
    matchLabels:
      app: sample-tomcat
  template:
    metadata:
      labels:
        app: sample-tomcat
        app.kubernetes.io/name: sample-tomcat
    spec:
      containers:
        - image: nalbam/sample-tomcat:v0.1.7
          name: sample-tomcat
          resources:
            limits:
              cpu: 1200m
              memory: 1228Mi
            requests:
              cpu: 1000m
              memory: 1024Mi
          envFrom:
            - configMapRef:
                name: sample-tomcat
