apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-tomcat
spec:
  selector:
    matchLabels:
      app: sample-tomcat
  template:
    metadata:
      labels:
        app: sample-tomcat
        app.kubernetes.io/name: sample-tomcat
        version: v0.3.17
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
    spec:
      containers:
        - image: nalbam/sample-tomcat:v0.3.17
          name: sample-tomcat
          resources:
            limits:
              cpu: 1200m
              memory: 1228Mi
            requests:
              cpu: 1000m
              memory: 1024Mi
          envFrom:
            - configMapRef:
                name: sample-tomcat
