apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: sample-tomcat
    app.kubernetes.io/name: sample-tomcat
  name: sample-tomcat
data:
  PROFILE: dev
  VERSION: v0.3.16
  MESSAGE: hello dev-demo world
