apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: sample-tomcat
    app.kubernetes.io/name: sample-tomcat
  name: sample-tomcat
data:
  PROFILE: dev
  VERSION: v0.4.5
  MESSAGE: hello dev-demo world
  # DD_AGENT_ENABLED: "true"
  JAVA_AGENT_ENABLED: "true"
