apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-tomcat
spec:
  selector:
    matchLabels:
      app: sample-tomcat
  template:
    metadata:
      labels:
        app: sample-tomcat
        app.kubernetes.io/name: sample-tomcat
        version: v0.2.6
    spec:
      containers:
        - image: nalbam/sample-tomcat:v0.2.6
          name: sample-tomcat
          resources:
            limits:
              cpu: 600m
              memory: 614Mi
            requests:
              cpu: 500m
              memory: 512Mi
          envFrom:
            - configMapRef:
                name: sample-tomcat
