# chart-repo: custom/sample-node
# chart-version: latest
# chart-ingress: true

profile: dev

image:
  repository: nalbam/sample-node
  tag: alpine

pod:
  labels:
    spotinst.io/pods-contingency: "true"
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"

# pdb:
#   minAvailable: "20%"
#   maxUnavailable: "20%"

service:
  type: ClusterIP

ingress:
  enabled: true
  hosts:
    - sample-node-sample.spot.nalbam.com
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

configmap:
  enabled: false
secret:
  enabled: false
