prometheus:
  enabled: true

  server:
    persistentVolume:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 8Gi
      # storageClass: "efs"
      existingClaim: prometheus-server

  alertmanager:
    persistentVolume:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 2Gi
      # storageClass: "efs"
      existingClaim: prometheus-alertmanager

  kubeStateMetrics:
    enabled: KUBE_STATE_METRICS
