grafana:
  enabled: true

  adminUser: admin
  adminPassword: PASSWORD

  service:
    type: SERVICE_TYPE

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
      external-dns.alpha.kubernetes.io/hostname: "INGRESS_DOMAIN."
    hosts:
      - INGRESS_DOMAIN
    tls:
      - secretName: grafana-tls
        hosts:
          - INGRESS_DOMAIN

  env:
    GF_SERVER_ROOT_URL: https://INGRESS_DOMAIN

  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 5Gi
    # storageClassName: "efs"
    existingClaim: grafana

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-server
          access: proxy
          isDefault: true

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "default"
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

  dashboards:
    default:
      kube-cluster:
        url: https://raw.githubusercontent.com/nalbam/helm-cui/master/templates/grafana/kube-cluster.json
        datasource: Prometheus
      kube-deployment:
        url: https://raw.githubusercontent.com/nalbam/helm-cui/master/templates/grafana/kube-deployment.json
        datasource: Prometheus
      nginx-ingress:
        url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/nginx.json
        datasource: Prometheus
      argo-cd:
        url: https://raw.githubusercontent.com/argoproj/argo-cd/master/examples/dashboard.json
        datasource: Prometheus
