apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: sample-node
    app.kubernetes.io/name: sample-node
  name: sample-node
data:
  PROFILE: dev
  VERSION: v0.4.14
  MESSAGE: hello dev-demo world
  FAULT_RATE: "5"
  # TRACER: "datadog"
