apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: sample-node
    app.kubernetes.io/name: sample-node
  name: sample-node
spec:
  # replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: sample-node
  strategy:
    blueGreen:
      activeService: sample-node
      autoPromotionEnabled: true
      autoPromotionSeconds: 30
      # prePromotionAnalysis:
      #   # templates:
      #   #   - templateName: http-benchmark
      #   templateName: http-benchmark
      #   args:
      #     - name: url
      #       value: http://sample-node-preview:3000/success/98
      # previewReplicaCount: 1
      previewService: sample-node-preview
      # scaleDownDelaySeconds: 30
  template:
    metadata:
      labels:
        app: sample-node
        app.kubernetes.io/name: sample-node
        version: v0.4.16
    spec:
      containers:
        - image: nalbam/sample-node:v0.4.16
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: sample-node
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 100m
              memory: 120Mi
            limits:
              cpu: 110m
              memory: 134Mi
          envFrom:
            - configMapRef:
                name: sample-node
