apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: sample-node
    app.kubernetes.io/name: sample-node
  name: sample-node
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: sample-node
  strategy:
    blueGreen:
      activeService: sample-node
      autoPromotionEnabled: false
      autoPromotionSeconds: 30
      prePromotionAnalysis:
        # templates:
        #   - templateName: success-rate
        templateName: http-benchmark
        args:
          - name: url
            value: http://sample-node-dev-preview:3000/success/33
      # previewReplicaCount: 1
      previewService: sample-node-preview
      # scaleDownDelaySeconds: 30
    # canary:
    #   canaryService: sample-node-preview
    #   steps:
    #     - experiment:
    #         duration: 60s
    #         templates:
    #           - name: experiment
    #             specRef: canary
    #         analysis:
    #           - name: load-test
    #             # templates:
    #             #   - templateName: http-benchmark
    #             templateName: http-benchmark
    #             args:
    #               - name: url
    #                 value: https://sample-node-dev-preview.demo.mzdev.be/success/99
  template:
    metadata:
      labels:
        app: sample-node
        app.kubernetes.io/name: sample-node
        version: v0.3.174
    spec:
      containers:
        - image: nalbam/sample-node:v0.3.174
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: sample-node
          ports:
            - containerPort: 3000
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 100m
              memory: 120Mi
            limits:
              cpu: 110m
              memory: 134Mi
          envFrom:
            - configMapRef:
                name: sample-node
