apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: sample-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-node
  strategy:
    blueGreen:
      activeService: sample-node
      autoPromotionEnabled: false
      autoPromotionSeconds: 30
      previewReplicaCount: 2
      previewService: sample-node-preview
      scaleDownDelaySeconds: 10
  template:
    metadata:
      labels:
        app: sample-node
        app.kubernetes.io/name: sample-node
    spec:
      containers:
        - image: nalbam/sample-node:v0.3.47
          name: sample-node
          resources:
            limits:
              cpu: 120m
              memory: 153Mi
            requests:
              cpu: 100m
              memory: 128Mi
          envFrom:
            - configMapRef:
                name: sample-node
