apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: sample-node
    app.kubernetes.io/name: sample-node
  name: sample-node
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: sample-node
  strategy:
    canary:
      canaryService: sample-node-preview
      steps:
        # - setWeight: 10
        # - pause: {}
        - experiment:
            duration: 120
            templates:
              - name: baseline
                specRef: stable
              - name: canary
                specRef: canary
            analysis:
              templateName: webmetric
              args:
                - name: url
                  value: "https://sample-node-dev.demo.mzdev.be/success/99"
        - setWeight: 20
        - pause: { duration: 30 }
        - setWeight: 40
        - pause: { duration: 30 }
        - setWeight: 60
        - pause: { duration: 30 }
        - setWeight: 80
        - pause: { duration: 30 }
  template:
    metadata:
      labels:
        app: sample-node
        app.kubernetes.io/name: sample-node
        version: v0.3.138
    spec:
      containers:
        - image: nalbam/sample-node:v0.3.138
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: sample-node
          ports:
            - containerPort: 3000
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 100m
              memory: 120Mi
            limits:
              cpu: 110m
              memory: 134Mi
          envFrom:
            - configMapRef:
                name: sample-node
