apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: sample-node
    app.kubernetes.io/name: sample-node
  name: sample-node
spec:
  minReplicas: 2
  maxReplicas: 8
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: sample-node
  # targetCPUUtilizationPercentage: 80
  metrics:
    # use a "Pods" metric, which takes the average of the
    # given metric across all pods controlled by the autoscaling target
    - type: Pods
      pods:
        # use the metric that you used above: pods/container_network_receive_bytes
        metricName: container_network_receive_bytes
        # target 500 milli-requests per second,
        # which is 1 request every two seconds
        targetAverageValue: 2k
