kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  labels:
    app: sample-node
    app.kubernetes.io/name: sample-node
    release: prometheus-operator
  name: sample-node
spec:
  selector:
    matchLabels:
      app: sample-node
  endpoints:
    - port: http
