apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: sample-webpack
    app.kubernetes.io/name: sample-webpack
  name: sample-webpack
data:
  PROFILE: dev
  VERSION: v0.2.1
  MESSAGE: hello dev-demo world
