apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opspresso:config-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opspresso:config-admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: developer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opspresso:view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: readonly
