# chart-repo: custom/sample-tomcat
# chart-version: latest
# chart-ingress: true

profile: dev

image:
  repository: nalbam/sample-tomcat
  tag: alpine

service:
  type: ClusterIP

ingress:
  enabled: true
  basedomain:
  hosts:
    - sample-tomcat-dev.demo.nalbam.com
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

configmap:
  enabled: false
secret:
  enabled: false
