fullnameOverride: sample-tomcat

profile: dev

namespace: dev

image:
  repository: nalbam/sample-tomcat
  tag: v0.0.23

ingress:
  enabled: true
  basedomain:
  hosts:
    - sample-tomcat-dev.demo.nalbam.com
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

configmap:
  enabled: true
  data:
    MESSAGE: "hello dev world"

secret:
  enabled: true
  data:
    SECRET: c2VjcmV0IHdvcmxkCg==
