apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: sample-prod
  labels:
    app: sample-prod
spec:
  secretName: sample-prod-tls
  issuerRef:
    name: letsencrypt-issuer-prod
    kind: ClusterIssuer
  dnsNames:
    - sample-node.demo.mzdev.be
    - sample-spring.demo.mzdev.be
    - sample-tomcat.demo.mzdev.be
    - sample-web.demo.mzdev.be
    - sample-webpack.demo.mzdev.be
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - sample-node.demo.mzdev.be
          - sample-spring.demo.mzdev.be
          - sample-tomcat.demo.mzdev.be
          - sample-web.demo.mzdev.be
          - sample-webpack.demo.mzdev.be
