apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: sample-web
    app.kubernetes.io/name: sample-web
  name: sample-web
data:
  PROFILE: prod
  VERSION: v0.2.5
  MESSAGE: hello prod-demo world
