apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-web
spec:
  selector:
    matchLabels:
      app: sample-web
  template:
    metadata:
      labels:
        app: sample-web
        app.kubernetes.io/name: sample-web
    spec:
      containers:
        - image: nalbam/sample-web:v0.2.1
          name: sample-web
          resources:
            limits:
              cpu: 120m
              memory: 153Mi
            requests:
              cpu: 100m
              memory: 128Mi
          envFrom:
            - configMapRef:
                name: sample-web
